title: Open Access Feminist Resources
baseurl: "/freefeminist-resources"
url: "https://junipertreed.github.io"
theme: minima
collections:
  tags:
    output: true
    permalink: /tags/:title
  vocab:
    output: true
    permalink: /vocab/:title
    order: 
    - patriarchy.md
    - misogyny.md
    - gender.md
    - sex.md
    - objectification.md
    - oppression.md
    - domestic_labor.md
  ideologies:
    output: true
    permalink: /ideologies/:title
  movements:
    output: true
    permalink: /movements/:title
  articles: 
    output: true
    permalink: /articles/:title
  books:
    output: true
    permalink: /books/:title
  people:
    output: true
    permalink: /people/:title

defaults:
  -scope:
    type: "tags"
  values:
    layout: tag_item

defaults:
  - scope:
      type: "theories"
    values:
      layout: theory_item

defaults:
  - scope: 
      type: "ideologies"
    values:
      layout: ideology_item

defaults:
  - scope:
      type: "vocab"
    values:
      layout: vocab_item

defaults:
  - scope:
      type: "movements"
    values:
      layout: movement_item

defaults:
  -scope:
    type: "articles"
  values:
    layout: article_item

defaults:
  - scope:
      type: "books"
    values:
      layout: book_item

defaults:
  -scope:
    type: "people"
    values:
      layout: person_item